### ISSUE TITLE
Adjust `miscellaneous_test.py` and split tests into different functions

### ISSUE THREAD

**Issue by VVVENIIDIICI** [FHDA/API_deployment#20]
Today, all the test cases are all in `test_example_hashtag` function. Would it be better to split API tests into different functions?

 e.g.
```
class MiscellaneousTest(BaseTest):
    def hashtag_get_test(self):
        ...
    def hashtag_post_test(self):
       ...
```

**Comment by yifeili98** [comment]
That sounds like a good practice, I will make split the functions later today.

**Comment by VVVENIIDIICI** [comment]
Thanks! No rush at all!
